<?php

namespace AppBundle\Repository;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPendingStatus()
    {
        return $this->findBy(
            array('status' => 'Oczekuje na wpłatę'),
            array('orderTime' => 'ASC')
        );
    }

    public function findByUser($user)
    {
        return $this->findBy(array(
            'userId' => $user
        ));
    }

    public function findByTimeRangeAndStatus($timeRange, $status)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('o')
            ->from('AppBundle:Orders', 'o')
            ->where('o.orderTime BETWEEN :timeRange AND o.orderTime AND o.status = :status')
            ->setParameters(array(
                'timeRange' => $timeRange,
                'status' => $status
            ))
            ->orderBy('o.orderTime', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function findOrdersByIds($orderIds)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('o')
            ->from('AppBundle:Orders', 'o')
            ->where($qb->expr()->in('o.id', $orderIds));

        return $qb->getQuery()->getResult();
    }
}
