<?php

namespace AppBundle\Repository;

/**
 * OrderedProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderedProductsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByProductId($id)
    {
        return $this->findBy(array(
            'productId' => $id
        ));
    }

    public function findById($id)
    {
        return $this->findBy(array(
            'id' => $id
        ));
    }

    public function findByOrderId($orderId)
    {
        return $this->findBy(array(
            'orderId' => $orderId
        ));
    }

    public function findByReservation($orders)
    {
        return $this->findBy(
            array(
                'orderId' => ($orders),
                'productStatus' => array('Częściowa rezerwacja, oczekuje na dostawę', 'Brak towaru, oczekuje na dostawę')
            )
        );
    }

    public function findAllPending()
    {
        return $this->findBy(array(
            'productStatus' => array('Częściowa rezerwacja, oczekuje na dostawę', 'Brak towaru, oczekuje na dostawę', 'Towar częściowo zarezerwowany')
        ));
    }

    public function findOrders($id)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('o.order')
            ->from('AppBundle:OrderedProducts', 'o')
            ->where('o.productId = :id')
            ->setParameter('id', $id);

        return $qb->getQuery()->getArrayResult();
    }

    public function findLastByDate()
    {

    }
}
