<?php

namespace AppBundle\Repository;

/**
 * SupplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplyRepository extends \Doctrine\ORM\EntityRepository
{
}
